### PR TITLE
Fix docker cp

### LINKED ISSUE #18: docker cp not working properly
Hello, 
Fist of all, thanks for the driver and the work you put into it, it's great, it saves me a lot of time when creating containers.

I discovered a bug, the issue is the following:
When I start the container the volume correctly mounts.
Then, while the container is running I run a "docker cp".
When the "docker cp" ends the volume unmounts (i.e. the "mountpoint" folder is no longer there)
The running container does not like that.

Doing a "docker cp" with an stopped container or starting and stoping the container work just fine.

If you could fix it or give me some indications on where to look would be really nice (I cannot do it without help due to my total lack of knowledge of Go and Docker drivers)

Thans!

### PR DESCRIPTION
**Pull request by andergnet**
This pull request fixes issue #18

### CODE REVIEW

File: driver.go [hunk 1]
```diff
@@ -273,40 +233,20 @@ func (d *DockerOnTop) Unmount(request *volume.UnmountRequest) error {
...
-		log.Criticalf("Failed to remove the active mount file: %v. The volume is now considered used by a container "+
-			"that no longer exists", err)
-		// The user most likely won't see this error message due to daemon not showing unmount errors to the
-		// `docker run` clients :((
-		return fmt.Errorf("docker-on-top internal error: failed to remove the active mount file: %w. The volume is "+
-			"now considered used by a container that no longer exists. Human interaction is required: remove the file "+
-			"manually to fix the problem", err)
+		log.Debugf("Unmounted volume %s", request.Name)
+	} else {
+		log.Debugf("Volume %s is still mounted. Indicating success without unmounting", request.Name)
```
Comment (kolayne) [inline driver.go:249]: I don't agree with the error message change here. Here, you're seemingly saying "still mounted so I'm not unmounting it", which doesn't make sense. That's because of the ambiguity between "mounted" as in "a container is running where this volume is used" and "mounted" as in "the underlying overlay filesystem is present". IMO, the previous error message was clearer:
```go
log.Debugf("Volume %s is still mounted in some other container. Indicating success without unmounting", request.Name)
```

Maybe could be phrased even better, e.g., `Volume %s is still used in another container. Indicating success without unmounting`

File: activemount.go [hunk 2]
```diff
@@ -0,0 +1,110 @@
...
+	"os"
+
+	"github.com/docker/go-plugins-helpers/volume"
+)
+
+type ActiveMount struct {
+	UsageCount int
+}
+
+func (d *DockerOnTop) Activate(request *volume.MountRequest, activemountsdir lockedFile) (bool, error) {
```
Comment (kolayne) [inline activemount.go:17]: A comment on both `DockerOnTop.Activate` and `DockerOnTop.Activate`:

1.    Their names probably don't quite reflect what they do. If I saw the following piece of code:
      ```go
      var d DockerOnTop = ...
      d.Activate(...)
      ```
      I would most probably assume that `d.Activate` _activates_ the `d` object (whatever it could mean) because that's what the name suggests. But what it actually does is it activates _a volume_. If we had a proper volume object, it would make sense to move this method there and have `volume.Activate`, but as its a method of `DockerOnTop`, its name should probably be `ActivateVolume`

2.  In go, the case of the first letter (i.e., whether it's lowercase or uppercase) has a semantic effect: if an entity name is capitalized, it's _exported_ (i.e., public - available from other packages), otherwise it's _unexported_ (i.e., private, only available in this package). As I understand, the `.Activate` and `.Deactivate` are both intended for internal use only (a caller external to `DockerOnTop` shall not call them directly). If that's the case, their names should be changed.

3.  If I'm wrong and you intended that these functions are exported, it's a go convention to have a documentation string for every exported entity (see [Documenting go code](https://go.dev/blog/godoc) for details). You may notice that other exported methods of `DockerOnTop` don't have documentation, which is a flaw, but all of them correspond to Docker API calls, whereas the two new functions you are adding are something new.

4.  Finally, as you may notice in further comments, at some points it wasn't clear to me what these functions should do and, especially, what they should return. That's why, even if you didn't mean to export them and you'll rename them to `.activateVolume` and `.deactivateVolume` respectively, they would still benefit from a short docstring that explains what they do and what they return.

File: activemount.go [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+	"encoding/json"
+	"errors"
+	"fmt"
+	"io"
+	"os"
+
+	"github.com/docker/go-plugins-helpers/volume"
+)
+
+type ActiveMount struct {
```
Comment (kolayne) [inline activemount.go:13]: You probably meant to call it `activeMount` (see point 2 of the next note, on exporting entities in go).
(note that unlike the structure, its field _should_ be exported: otherwise `json.Marshal`/`.Unmarshal` won't be able to access it, as they are not part of this package)

**Review by kolayne — CHANGES_REQUESTED** [review]
Good evening! Sorry, I didn't notice the PR when you opened it and then didn't check my email for almost a week... :sob: 

But here I am :)

Firstly, thank you for the PR! There are some changes that I request below. Please, see my comments and let me know if I misunderstood something that you did intentionally.

Second, a general note (too late for this PR but may be useful for your future contributions): when your PR, while addressing a single problem, can be broken down into logical sub-steps, which you take to implement the patch, many maintainers prefer that you make a commit per step, so that your changes can be reviewed step by step as well. For example, I see two logical sub-steps of this PR: first, separate the existing code between driver.go and activemount.go, next, patch the multiple-mount logic.

Btw, providing detailed commit messages, answering the what&why questions ("what did you do? why did you do that?") is also beneficial and gives the reviewer an insight into your changes before they even starts reading your code!

<br>

UPD: on this page my comments are displayed in the order I created them, but it's better if you read them along with the code, in the order they appear in the [Files changed](https://github.com/kolayne/docker-on-top/pull/20/files) section

File: driver.go [hunk 4]
```diff
@@ -184,10 +183,10 @@ func (d *DockerOnTop) Mount(request *volume.MountRequest) (*volume.MountResponse
...
-	if errors.Is(readDirErr, io.EOF) {
-		// No files => no other containers are using the volume. Need to mount the overlay
-
+	mount, err := d.Activate(request, activemountsdir)
+	if err != nil {
+		return nil, internalError("failed to activate the active mount:", err)
+	} else if mount {
 		lowerdir := thisVol.BaseDirPath
 		upperdir := d.upperdir(request.Name)
 		workdir := d.workdir(request.Name)
```
Comment (kolayne) [inline driver.go:192]: Read [this comment](https://github.com/kolayne/docker-on-top/pull/20/files#r1693985907) first.

<br>

Here you, unfortunately, did kind of the opposite (similarly, you reversed the original order, but it has the inverse effect in this case).

Combining the logic inside `d.Activate` and the code _below_ this comment up to and including the `syscall.Mount` (that's the code you did not modify), the overall (new) logic is as follows:

- Check if the volume is already mounted based on `activemount` files. If it's not:
- Create a new `activemount` file to indicate that I am the user of the volume \[may fail\]
- Perform the actual mount of the `overlay` \[may fail\]

Now, imagine the file creation step succeeds but the next one fails. For that container, of course, we'll report the error and it will refuse to start, but the volume ends up in a _very bad_ state. If another container tries to use that same volume, it will perform the same steps above, but in the first one it will find an activemount file from the previous container and will assume that the volume is already mounted, while it in fact is not!!

The reverse order is not very good either but slightly better: if the first container manages to mount the volume but doesn't manage to mark it as mounted, it, likewise, won't let the current container start (so that `overlay` mount remains unused), then, when the next container attempts a mount, it will run the same steps and, in the trickiest case, will just mount the same `overlay` on top of the old one and start using it (which is weird because there are two `overlay`s mounted simultaneously using the same internal directories, but should be ok, as the first overlay is never used, being shadowed by the new one).

<hr>

So,

1. First possible improvement for your code: your implementation should at least emit a scary screaming error! (see [this example](https://github.com/kolayne/docker-on-top/blob/1bfffce2ff8960b549a9d5fb0a894895163e5ca6/driver.go#L301-L309) from the old code - this error was used in a very similar situation)
2. Second, it would be much better if you could fix things such that the order of the system calls (mount/unmount call and activemount file creation/deletion call) is old (as in my code) for the `Mount` operation but is new (as in your code) for the `Unmount` operation.

In fact, I now see how it's possible to completely fix the problem in the `Mount` part, so that we never even attempt to mount `overlay` on top of anything old. Of course, this is out of scope of this PR, so I'll create a separate issue (but it still requires that you restore the old order here in `Mount`)

File: activemount.go (hunk 3 above)
Comment (andergnet) [reply activemount.go]: It's my first real program in Go, I had no idea about that, I simply copied how `VolumeInfo` was defined. I have fixed it.

File: activemount.go (hunk 2 above)
Comment (andergnet) [reply activemount.go]: I hope this looks better now with the changes I have done:
Commit: b18043e55f229afdeb0243239d7f25d55d012173

File: activemount.go [hunk 5]
```diff
@@ -0,0 +1,110 @@
...
+	UsageCount int
+}
+
+func (d *DockerOnTop) Activate(request *volume.MountRequest, activemountsdir lockedFile) (bool, error) {
+	var activeMount ActiveMount
```
[the remark this answers is not in the document]
Comment (andergnet) [reply activemount.go]: Fixed 7043a09038fa4b8000db47c9ab3f1d4d99ea832d

File: activemount.go [hunk 6]
```diff
@@ -0,0 +1,110 @@
...
+		log.Errorf("Failed to list the activemounts directory: %v", readDirErr)
+		return false, fmt.Errorf("failed to list activemounts/ %v", readDirErr)
+	}
+
+	var activeMount ActiveMount
+	activemountFilePath := d.activemountsdir(request.Name) + request.ID
+
+	otherVolumesPresent := len(dirEntries) > 1 || dirEntries[0].Name() != request.ID
+
+	file, err := os.Open(activemountFilePath)
```
[the remark this answers is not in the document]
Comment (andergnet) [reply activemount.go]: Fixed: c0d28c03e0834a7b8b2fda8039376bbf41fe25ea

File: activemount.go [hunk 7]
```diff
@@ -0,0 +1,110 @@
...
+		// Default case, we need to create a new active mount, the filesystem needs to be mounted
+		activeMount = ActiveMount{UsageCount: 0}
+	} else {
+		log.Errorf("Active mount file %s exists but cannot be read.", activemountFilePath)
+		return false, fmt.Errorf("active mount file %s exists but cannot be read", activemountFilePath)
+	}
+
+	activeMount.UsageCount++
+
+	payload, _ := json.Marshal(activeMount)
```
[the remark this answers is not in the document]
Comment (andergnet) [reply activemount.go]: _it's not clear to me why. json.Marshal's behavior should be much more predictable than that of json.Unmarshal_
We have control over what the Marshal-ed structure (activeMount) so we will not get suprises there. Unmarshal, on the other hand, deals with a file in the filesystem and we could have a surprise if someone changes it.

I have added a comment to indicate why it is safe to ignore the error, which basically boils down to the fact that there is no room for error when converting an structure containing a single integer to JSON.
03f2054204f32b32c670c3b866301210b7518652

File: activemount.go [hunk 8]
```diff
@@ -0,0 +1,110 @@
...
+	err = os.WriteFile(activemountFilePath, payload, 0o666)
```
[the remark this answers is not in the document]
Comment (andergnet) [reply activemount.go]: Indeed, 0764601aad29eeb7de353eb28e26a5f3be7aad89

File: activemount.go [hunk 9]
```diff
@@ -0,0 +1,110 @@
...
+
+	if activeMount.UsageCount == 0 {
+		err := os.Remove(activemountFilePath)
+		if err != nil {
+			log.Errorf("The active mount file %s could not be deleted", activemountFilePath)
+			return false, fmt.Errorf("the active mount file %s could not be deleted", activemountFilePath)
+		}
+		return !otherVolumesPresent, nil
+	} else {
+		payload, _ := json.Marshal(activeMount)
```
[the remark this answers is not in the document]
Comment (andergnet) [reply activemount.go]: 03f2054204f32b32c670c3b866301210b7518652

File: activemount.go [hunk 10]
```diff
@@ -0,0 +1,110 @@
...
+		err = os.WriteFile(activemountFilePath, payload, 0o666)
```
[the remark this answers is not in the document]
Comment (andergnet) [reply activemount.go]: You give me too much credit 😉, I probably copy-pasted that from somewhere else and didn't give it a second thought. Thankfully revisions exist.
0764601aad29eeb7de353eb28e26a5f3be7aad89

File: driver.go [hunk 11]
```diff
@@ -184,10 +183,10 @@ func (d *DockerOnTop) Mount(request *volume.MountRequest) (*volume.MountResponse
 	}
 	defer activemountsdir.Close() // There is nothing I could do about the error (logging is performed inside `Close()` anyway)
 
-	_, readDirErr := activemountsdir.ReadDir(1) // Check if there are any files inside activemounts dir
-	if errors.Is(readDirErr, io.EOF) {
-		// No files => no other containers are using the volume. Need to mount the overlay
-
+	mount, err := d.Activate(request, activemountsdir)
```
[the remark this answers is not in the document]
Comment (andergnet) [reply driver.go]: Changed to doMountFs also to differenciate between the two meanings of "Mount".
1985b5201fee166a4fba0d11e1a8c1026c247f02

File: activemount.go (hunk 2 above)
Comment (andergnet) [reply activemount.go]: Also commit 3a67652e35100e08b72481ca830ffc1c62d54e19 since I didn't properly rename `deactivateVolume`

File: activemount.go [hunk 12]
```diff
@@ -0,0 +1,110 @@
...
+	"github.com/docker/go-plugins-helpers/volume"
+)
+
+type ActiveMount struct {
+	UsageCount int
+}
+
+func (d *DockerOnTop) Activate(request *volume.MountRequest, activemountsdir lockedFile) (bool, error) {
+	var activeMount ActiveMount
+	var result bool
```
[the remark this answers is not in the document]
Comment (andergnet) [reply activemount.go]: Since this was an issue also in driver.go (see [comment](https://github.com/kolayne/docker-on-top/pull/20/files/bb0d01096262eea9b5f04e53851963f7f45fe453#r1694002909)), I have named it the same way everywhere: 1985b5201fee166a4fba0d11e1a8c1026c247f02

File: activemount.go [hunk 13]
```diff
@@ -0,0 +1,110 @@
...
+		payload, _ := io.ReadAll(file)
+		json.Unmarshal(payload, &activeMount)
+		file.Close()
+	} else if os.IsNotExist(err) {
+		// Default case, we need to create a new active mount, the filesystem needs to be mounted
+		activeMount = ActiveMount{UsageCount: 0}
+	} else {
+		log.Errorf("Active mount file %s exists but cannot be read.", activemountFilePath)
+		return false, fmt.Errorf("active mount file %s exists but cannot be read", activemountFilePath)
+	}
```
[the remark this answers is not in the document]
Comment (andergnet) [reply activemount.go]: I have applied the suggestions as they do make good sense. As if it was intended, the case and punctuation changes they were, initially they where the same with human readable format (casing and sentence ending dots) but the linter complained about that format on the error message. That's how it ended up like this. 

c57da7724d6098d4bcb9ec34cb4a554b370576a6
f9aadb4df4833d2d81d15aee3ed93c30c52f9ba6

File: activemount.go [hunk 14]
```diff
@@ -0,0 +1,110 @@
...
+
+	activeMount.UsageCount++
+
+	payload, _ := json.Marshal(activeMount)
+	err = os.WriteFile(activemountFilePath, payload, 0o666)
+	if err != nil {
+		log.Errorf("Active mount file %s cannot be written.", activemountFilePath)
+		return false, fmt.Errorf("active mount file %s cannot be written", activemountFilePath)
+	}
```
[the remark this answers is not in the document]
Comment (andergnet) [reply activemount.go]: c57da7724d6098d4bcb9ec34cb4a554b370576a6
f9aadb4df4833d2d81d15aee3ed93c30c52f9ba6

File: activemount.go [hunk 15]
```diff
@@ -0,0 +1,110 @@
...
+	return result, nil
+}
+
+func (d *DockerOnTop) Deactivate(request *volume.UnmountRequest, activemountsdir lockedFile) (bool, error) {
+
+	dirEntries, readDirErr := activemountsdir.ReadDir(2) // Check if there is any _other_ container using the volume
+	if errors.Is(readDirErr, io.EOF) {
+		// If directory is empty, unmount overlay and clean up
+		log.Errorf("There are no active mount files and one was expected. Unmounting.")
+		return true, fmt.Errorf("there are no active mount files and one was expected. Unmounting")
```
[the remark this answers is not in the document]
Comment (andergnet) [reply activemount.go]: c57da7724d6098d4bcb9ec34cb4a554b370576a6
f9aadb4df4833d2d81d15aee3ed93c30c52f9ba6

File: activemount.go [hunk 16]
```diff
@@ -0,0 +1,110 @@
...
+		payload, _ := io.ReadAll(file)
+		json.Unmarshal(payload, &activeMount)
+		file.Close()
+	} else if os.IsNotExist(err) {
+		log.Errorf("The active mount file %s was expected but is not there", activemountFilePath)
+		return !otherVolumesPresent, fmt.Errorf("the active mount file %s was expected but is not there", activemountFilePath)
+	} else {
+		log.Errorf("The active mount file %s could not be opened", activemountFilePath)
+		return false, fmt.Errorf("the active mount file %s could not be opened", activemountFilePath)
+	}
```
[the remark this answers is not in the document]
Comment (andergnet) [reply activemount.go]: c57da7724d6098d4bcb9ec34cb4a554b370576a6
f9aadb4df4833d2d81d15aee3ed93c30c52f9ba6

File: activemount.go [hunk 17]
```diff
@@ -0,0 +1,110 @@
...
+			log.Errorf("The active mount file %s could not be deleted", activemountFilePath)
+			return false, fmt.Errorf("the active mount file %s could not be deleted", activemountFilePath)
+		}
+		return !otherVolumesPresent, nil
+	} else {
+		payload, _ := json.Marshal(activeMount)
+		err = os.WriteFile(activemountFilePath, payload, 0o666)
+		if err != nil {
+			log.Errorf("The active mount file %s could not be updated", activemountFilePath)
+			return false, fmt.Errorf("the active mount file %s could not be updated", activemountFilePath)
```
[the remark this answers is not in the document]
Comment (andergnet) [reply activemount.go]: c57da7724d6098d4bcb9ec34cb4a554b370576a6
f9aadb4df4833d2d81d15aee3ed93c30c52f9ba6

File: driver.go (hunk 1 above)
Comment (andergnet) [reply driver.go]: I like the one you proposed, it's more clear of what's happening:
197c6feb30581a079b201dab667119abb8009af1

File: activemount.go [hunk 18]
```diff
@@ -0,0 +1,110 @@
...
+	}
+
+	activemountFilePath := d.activemountsdir(request.Name) + request.ID
+	file, err := os.Open(activemountFilePath)
+
+	if err == nil {
+		// The file can exist from a previous mount when doing a docker cp on an already mounted container, no need to mount the filesystem again
+		payload, _ := io.ReadAll(file)
+		json.Unmarshal(payload, &activeMount)
+		file.Close()
```
[the remark this answers is not in the document]
Comment (andergnet) [reply activemount.go]: Fixed: f6634d9b5dabdaaa5322ea9b4f000a8fed5bbcc0

File: activemount.go [hunk 19]
```diff
@@ -0,0 +1,110 @@
...
+	activemountFilePath := d.activemountsdir(request.Name) + request.ID
+
+	otherVolumesPresent := len(dirEntries) > 1 || dirEntries[0].Name() != request.ID
+
+	file, err := os.Open(activemountFilePath)
+
+	if err == nil {
+		payload, _ := io.ReadAll(file)
+		json.Unmarshal(payload, &activeMount)
+		file.Close()
```
[the remark this answers is not in the document]
Comment (andergnet) [reply activemount.go]: Fixed: f6634d9b5dabdaaa5322ea9b4f000a8fed5bbcc0

File: activemount.go [hunk 20]
```diff
@@ -0,0 +1,110 @@
...
+		return false, fmt.Errorf("the active mount file %s could not be opened", activemountFilePath)
+	}
+
+	activeMount.UsageCount--
+
+	if activeMount.UsageCount == 0 {
+		err := os.Remove(activemountFilePath)
+		if err != nil {
+			log.Errorf("The active mount file %s could not be deleted", activemountFilePath)
+			return false, fmt.Errorf("the active mount file %s could not be deleted", activemountFilePath)
```
[the remark this answers is not in the document]
Comment (andergnet) [reply activemount.go]: I'm not really convinced with the new text either, if you have a suggestion please do not hesitate to propose.
Now that the log messages are handled in driver.go, i would keep all of them as Errorf and not Criticalf for the sake of simplicity and the fact that I do not consider the errors more severe.
e441320f90110aebe797cc8e412f493e2a59cd81

File: driver.go (hunk 4 above)
Comment (andergnet) [reply driver.go]: I have improved the way Mount function works, I keep the new order but in case the filesystem mount fails it will undo the `activemount` creation so it returns the function in a consistent state: filesystem not mounted and no activemount present.

01de48d2fe2c0cfc4fb01f1fd34247ca88a11e98

**Comment by andergnet** [comment]
@kolayne I think I have addressed all the issues you raised in the review. Could you please review it again?

I tried to be more transparent and show every step of the way but I'm not used to do it, so my apologies if you expected something different. 
I won't have access to a proper computer for a few weeks, don't worry if I do not answer I'll do it when I'm back.

File: activemount.go [hunk 21]
```diff
@@ -0,0 +1,152 @@
...
+
+	if err == nil {
+		// The file can exist from a previous mount when doing a docker cp on an already mounted container, no need to mount the filesystem again
+		payload, readErr := io.ReadAll(file)
+		closeErr := file.Close()
+		if readErr != nil {
+			return false, fmt.Errorf("active mount file %s has been opened but cannot be read %w", activemountFilePath, readErr)
+		} else if closeErr != nil {
+			return false, fmt.Errorf("active mount file %s has been opened but cannot be closed %w", activemountFilePath, readErr)
+		}
```
Comment (kolayne) [inline activemount.go:58]: Failing to close a file is bad enough to emit a warning but I don't think it's bad enough to abort the operation (if we read the contents successfully, there's no problem to continue). I'd do something like:
```go
if err := file.Close(); err != nil {
    log.Warningf("Failed to close active mount file: %v", err)
}
```

File: activemount.go [hunk 22]
```diff
@@ -0,0 +1,152 @@
...
+	}
+
+	var activeMountInfo activeMount
+	activemountFilePath := d.activemountsdir(requestName) + requestId
+	file, err := os.Open(activemountFilePath)
+
+	if err == nil {
+		// The file can exist from a previous mount when doing a docker cp on an already mounted container, no need to mount the filesystem again
+		payload, readErr := io.ReadAll(file)
+		closeErr := file.Close()
```
Comment (kolayne) [inline activemount.go:53]: I just noticed we open the file and then on success just read all contents of it and close it. Looks just like [`os.ReadFile`](https://pkg.go.dev/os#ReadFile). Can we use it here?

Fun fact: Go's standard library [ignores](https://github.com/golang/go/blob/86bec1ec198f2720c83bd232a72b800b4ea5a9f6/src/os/file.go#L792) the error returned by `file.Close()` inside `os.ReadFile`

File: activemount.go [hunk 23]
```diff
@@ -0,0 +1,152 @@
...
+		if readErr != nil {
+			return false, fmt.Errorf("active mount file %s has been opened but cannot be read %w", activemountFilePath, readErr)
+		} else if closeErr != nil {
+			return false, fmt.Errorf("active mount file %s has been opened but cannot be closed %w", activemountFilePath, readErr)
+		}
+		unmarshalErr := json.Unmarshal(payload, &activeMountInfo)
+		if unmarshalErr != nil {
```
Comment (kolayne) [inline activemount.go:60]: No big deal but looks a bit too verbose to me. Could be
```go
if err := json.Unmarshal(...); err != nil {
    do stuff
}
```

File: activemount.go [hunk 24]
```diff
@@ -0,0 +1,152 @@
...
+// actually requires to be mounted (as an overlay fs mount). For that purpose check if other containers
+// have already mounted the volume (by reading in `activemountsdir`). It is also possible that the volume
+// has already been been mounted by the same container (when doing a `docker cp` while the container is running),
+// in that case the file named with the `requestId` will contain the number of times the container has
+// been requested the volume to be mounted. That number will be increased each time `activateVolume` is
+// called and decreased on `deactivateVolume`.
+// Parameters:
+//
+//	requestName: Name of the volume to be mounted
+//	requestID: ID of the container requesting the mount
```
Comment (kolayne) [inline activemount.go:25]: Factual error: `reuqestID` is not a container id (which you see, e.g., in `docker container ls`). In fact, it is some id generated for the pair {container, volume}. The doc doesn't necessarily need to be this specific, but it should not lie either.

I would call it either "a container-volume-unique ID" or, more elaborate, "an ID unique among volumes and containers but the same value if a volume is mounted for a container twice". Maybe can be phrased better.

Please, also fix the same thing in `deactivateVolume`

File: activemount.go [hunk 25]
```diff
@@ -0,0 +1,152 @@
...
+// Parameters:
+//
+//	requestName: Name of the volume to be unmounted
+//	requestID: ID of the container requesting the unmount
+//	activemountsdir: Folder where Docker-On-Top mounts are tracked.
+//
+// Return:
+//
+//	doUnmountFs: Returns true if there are not other usages of this volume and the filesystem can be unmounted.
+//	err: If the function encountered an error, the error itself, nil if everything went right.
```
Comment (kolayne) [inline activemount.go:98]:
```suggestion
//	doUnmountFs: `true` if there are no other usages of this volume and the filesystem shall be unmounted
//		by the caller. **Must be respected even when an error is returned**!
//	err: An error, if encountered, `nil` otherwise.
```

File: activemount.go [hunk 26]
```diff
@@ -0,0 +1,152 @@
...
+// Parameters:
+//
+//	requestName: Name of the volume to be mounted
+//	requestID: ID of the container requesting the mount
+//	activemountsdir: Folder where Docker-On-Top mounts are tracked.
+//
+// Return:
+//
+//	doMountFs: Returns true if the request requires the filesystem to be mounted, false if not.
+//	err: If the function encountered an error, the error itself, nil if everything went right.
```
Comment (kolayne) [inline activemount.go:31]:
```suggestion
//	doMountFs: `true` if the caller shall mount the filesystem, `false` otherwise.
//		If an error is returned, `doMountFs` is always `false`.
//	err: An error, if encountered, `nil` otherwise.
```

File: activemount.go [hunk 27]
```diff
@@ -0,0 +1,152 @@
...
+//	doUnmountFs: Returns true if there are not other usages of this volume and the filesystem can be unmounted.
+//	err: If the function encountered an error, the error itself, nil if everything went right.
+func (d *DockerOnTop) deactivateVolume(requestName string, requestId string, activemountsdir lockedFile) (bool, error) {
+
+	dirEntries, readDirErr := activemountsdir.ReadDir(2) // Check if there is any _other_ container using the volume
+	if errors.Is(readDirErr, io.EOF) {
+		// If directory is empty, unmount overlay and clean up
+		return true, fmt.Errorf("there are no active mount files and one was expected. Unmounting")
+	} else if readDirErr != nil {
+		return false, fmt.Errorf("failed to list activemounts/ %v", readDirErr)
```
Comment (kolayne) [inline activemount.go:106]:
```suggestion
		return false, fmt.Errorf("failed to list activemounts/ : %w", readDirErr)
```

File: activemount.go [hunk 28]
```diff
@@ -0,0 +1,152 @@
...
+
+	otherVolumesPresent := len(dirEntries) > 1 || dirEntries[0].Name() != requestId
+	var activeMountInfo activeMount
+
+	activemountFilePath := d.activemountsdir(requestName) + requestId
+	file, err := os.Open(activemountFilePath)
+
+	if err == nil {
+		payload, readErr := io.ReadAll(file)
+		closeErr := file.Close()
```
Comment (kolayne) [inline activemount.go:117]: Same note as above: `os.ReadFile`

File: activemount.go [hunk 29]
```diff
@@ -0,0 +1,152 @@
...
+	} else {
+		return false, fmt.Errorf("the active mount file %s could not be opened %w, the filesystem won't be unmounted", activemountFilePath, err)
+	}
+
+	activeMountInfo.UsageCount--
+
+	if activeMountInfo.UsageCount == 0 {
+		err := os.Remove(activemountFilePath)
+		if err != nil {
+			return false, fmt.Errorf("the active mount file %s could not be deleted %w, the filesystem won't be unmounted", activemountFilePath, err)
```
Comment (kolayne) [inline activemount.go:138]: For consistency with an earlier error, indicating action ("unmount<i>ing</i>" / "refus<i>ing</i> to unmount")

```suggestion
			return false, fmt.Errorf("the active mount file %s could not be deleted: %w. Refusing to unmount", activemountFilePath, err)
```

File: activemount.go [hunk 30]
```diff
@@ -0,0 +1,152 @@
...
+		}
+		return !otherVolumesPresent, nil
+	} else {
+		// Convert activeMountInfo to JSON to store it in a file. We can safely ignore Marshal errors, since the
+		// activeMount structure is simple enought not to contain "strage" floats, unsupported datatypes or cycles
+		// which are the error causes for json.Marshal
+		payload, _ := json.Marshal(activeMountInfo)
+		err = os.WriteFile(activemountFilePath, payload, 0o644)
+		if err != nil {
+			return false, fmt.Errorf("the active mount file %s could not be updated %w, the filesystem won't be unmounted", activemountFilePath, err)
```
Comment (kolayne) [inline activemount.go:148]:
```suggestion
			return false, fmt.Errorf("the active mount file %s could not be written: %w. Refusing to unmount", activemountFilePath, err)
```

File: driver.go [hunk 31]
```diff
@@ -184,10 +183,11 @@ func (d *DockerOnTop) Mount(request *volume.MountRequest) (*volume.MountResponse
 	}
 	defer activemountsdir.Close() // There is nothing I could do about the error (logging is performed inside `Close()` anyway)
 
-	_, readDirErr := activemountsdir.ReadDir(1) // Check if there are any files inside activemounts dir
-	if errors.Is(readDirErr, io.EOF) {
-		// No files => no other containers are using the volume. Need to mount the overlay
-
+	doMountFs, err := d.activateVolume(request.Name, request.ID, activemountsdir)
+	if err != nil {
+		log.Errorf("Error while activating the filesystem mount: %w", err)
```
Comment (kolayne) [inline driver.go:188]: `%w` is a feature of `fmt.Errorf` only, when you want to create an error _object_. As `log.Errorf` just prints something, rather than creating an object, it uses `fmt.Sprintf` under the hood, which will either silently interpret `%w` as `%v`, or will display some warning or something. In any case,
```suggestion
		log.Errorf("Error while activating the filesystem mount: %v", err)
```

File: driver.go [hunk 32]
```diff
@@ -201,57 +201,29 @@ func (d *DockerOnTop) Mount(request *volume.MountRequest) (*volume.MountResponse
...
-				request.Name, err)
-			return nil, errors.New("failed to mount volume: something is missing (does the base directory " +
-				"exist?)")
-		} else if err != nil {
-			log.Errorf("Failed to mount overlay for volume %s: %v", request.Name, err)
-			return nil, internalError("failed to mount overlay", err)
+		if err != nil {
+			// The filesystem could not be mounted so undo the activateVolume call so it does not appear as if
+			// we are using a volume that we couln't mount. We can ignore the doUnmountFs because we know the volume
+			// is not mounted.
```
Comment (kolayne) [inline driver.go:207]: TODO for me: I will look into it more carefully some time later

File: driver.go [hunk 33]
```diff
@@ -273,40 +245,21 @@ func (d *DockerOnTop) Unmount(request *volume.UnmountRequest) error {
...
 
-	dirEntries, readDirErr := activemountsdir.ReadDir(2) // Check if there is any _other_ container using the volume
-	if len(dirEntries) == 1 || errors.Is(readDirErr, io.EOF) {
-		// If just one entry or directory is empty, unmount overlay and clean up
-
+	doUnmountFs, err := d.deactivateVolume(request.Name, request.ID, activemountsdir)
+	if err != nil {
+		log.Errorf("Error while activating the filesystem mount: %w", err)
+		return internalError("failed to deactivate the active mount:", err)
+	} else if doUnmountFs {
```
Comment (kolayne) [inline driver.go:252]: Oh-oh! From what I can see in the code of `.deactivateVolume`, it seems like you want this code to take actions for `doUnmountFs == true` even when `err != nil`! Am I right?

**Review by kolayne — CHANGES_REQUESTED** [review]
Nice! Here are some more things to fix

File: driver.go (hunk 33 above)
Comment (andergnet) [reply driver.go:252]: You are right, I did not notice there was a case returning true + error. I have changed it to log a warning instead and return true + nil

File: activemount.go [hunk 34]
```diff
@@ -0,0 +1,152 @@
...
+
+	_, readDirErr := activemountsdir.ReadDir(1) // Check if there are any files inside activemounts dir
+	if readDirErr == nil {
+		// There is something no need to mount the filesystem again
+		doMountFs = false
+	} else if errors.Is(readDirErr, io.EOF) {
+		// The directory is empty, mount the filesystem
+		doMountFs = true
+	} else {
+		return false, fmt.Errorf("failed to list activemounts/ %v", readDirErr)
```
[the remark this answers is not in the document]
Comment (andergnet) [reply activemount.go:42]: Done.

File: activemount.go (hunk 21 above)
Comment (andergnet) [reply activemount.go]: I have replaced everything with a os.ReadFile

File: activemount.go (hunk 23 above)
Comment (andergnet) [reply activemount.go:59]: If you don't have strong feelings about it I'll keep it the way it is with a single instruction per line, I find it better specially when debugging.

File: activemount.go (hunk 24 above)
Comment (andergnet) [reply activemount.go:25]: Done. I thought I checked it, but apparently not.

File: activemount.go (hunk 25 above)
Comment (andergnet) [reply activemount.go:96]: I have adapted your message because I have changed the behavior and now it never returns true when there is an error.

File: activemount.go (hunk 26 above)
Comment (andergnet) [reply activemount.go:30]: Done

File: activemount.go (hunk 27 above)
Comment (andergnet) [reply activemount.go:104]: Done

File: activemount.go (hunk 28 above)
Comment (andergnet) [reply activemount.go:115]: Done

File: activemount.go (hunk 29 above)
Comment (andergnet) [reply activemount.go:136]: Instead of changing all messages saying "the filesystem won't be unmounted" I changed the first one that said "Unmount" to "the filesystem will be unmounted (which now is a warning).

File: activemount.go (hunk 30 above)
Comment (andergnet) [reply activemount.go:146]: same as previous.

File: driver.go (hunk 31 above)
Comment (andergnet) [reply driver.go:188]: Done this one and another one in line 250.

**Comment by kolayne** [comment]
> I'm back!

Top!


> I think I have addressed all the issues you raised, please review again.


Hopefully, I'll be able to by the end of the week

> I know it's all in a single commit, sorry, it's an old habit, and by the time I noticed I had most of the changes already done.

No problem. This mostly matters at the beginning when I'm trying to understand what's the patch about in general. When the comments are addressed, I don't look into them one by one anyway.

**Comment by kolayne** [comment]
Hey, @andergnet!

I've found myself pretty busy with other stuff... So I don't really know when I'm going to get to merge this. That's somewhat untrivial, as I want to first merge some tests checking for some edge-case behaviors, and then merge your PR, making sure those tests pass (right now there's one scenario that is broken in master but, hopefully, with your PR, we can fix even that).

Yesterday I've made a step forward towards that, but I'm not quite there yet, and, given the experience of the last two months, I don't dare to try to estimate when I will have time to finish this.

But! I want to let you know that
1. Most likely, I won't request any more changes from you seem to have already done the core thing, and should there be minor issues, I can fix them myself;
2. I appreciate your attention to the project in general, and, in particular, the contribution with both the bug report and this workaround patch; and
3. Of course, sooner or later, this will definitely be merged!

**Comment by andergnet** [comment]
Hi @kolayne 
Glad to hear back from you, I was wondering what happened to you since you disappeared after being quite engaged in the topic, no complains, I just hope you are doing alright (I have a job a two daughters, I understand being busy for side projects like this).

About the MR being delayed, no problem on my side, it's your project, your rules ;-). Just let you know that I have been using docker-on-top in the last few months with the patch and I haven't run into any issues.

Till next time :-)

**Review by kolayne — APPROVED** [review]

**Comment by kolayne** [comment]
Hey, @andergnet, I have finally merged your changes!

As you may see, there was some code that I merged into master before your fix, then I rebased and restructured your code and merged it. FYI, the changes that I made to your patch are mostly cosmetic, except for one key amendment: the volume activation steps (mounting an overlay and creating an active mount file) and deactivation steps (removing the file and unmounting the overlay) are supposed to happen in the opposite order. So, I moved both actions into the functions you introduced, and added a note in driver.go to explain this order.

Anyway, thank you for submitting this fix (and inspiring another fix that I committed last week). By the way, hello from Korea - 안녕하세요!

**Comment by andergnet** [comment]
환영합니다, nice to see you around!
And I see you have come with presents ;-) The changes look good and the container management looks more solid now (even if it wasn't looking that bad before). I have already merged your changes into my branch (which I'm pointing to because it already had the fix for the cp) so I start using them.

Thanks again for the effort, it's very appreciated.
